version: "3"

services:



  loki:
    image: grafana/loki:latest
    user: "0"
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - /opt/monitoring/loki:/etc/loki
#    command: -config.file=/etc/loki/loki-config.yaml
#    restart: unless-stopped
    restart: always
    labels:
      org.label-schema.group: "monitoring"






  promtail:
    image: grafana/promtail:latest
    user: "0"
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /opt/monitoring/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
#    restart: unless-stopped
    restart: always
    labels:
      org.label-schema.group: "monitoring"

  





  grafana:
    image: grafana/grafana:latest
    user: "0"
    container_name: grafana
    ports:
      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_USER= admin        
#      - GF_SECURITY_ADMIN_PASSWORD= admin   
#      - GF_USERS_ALLOW_SIGN_UP= false
#    restart: unless-stopped
    restart: always
    labels:
      org.label-schema.group: "monitoring"
    volumes:
#      - grafana_data:/var/lib/grafana 
      - /opt/monitoring/grafana/data:/var/lib/grafana
      - /opt/monitoring/grafana/conf:/etc/grafana/conf
      - /opt/monitoring/grafana/provisioning:/etc/grafana/provisioning




  prometheus:
    image: prom/prometheus:latest
    user: "0"
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: always
#    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    volumes:
      - /opt/monitoring/prometheus:/etc/prometheus







  alertmanager:
    image: prom/alertmanager:latest
    user: "0"
    container_name: alertmanager
    volumes:
      - /opt/monitoring/alertmanager/config:/etc/alertmanager/config
      - /opt/monitoring/alertmanager/data:/etc/alertmanager/data
    restart: always
#    restart: unless-stopped
    ports:
      - "9093:9093"
    labels:
      org.label-schema.group: "monitoring"  






  nodeexporter:
    image: prom/node-exporter:latest
    user: "0"
    container_name: nodeexporter
    volumes:
      - /opt/monitoring/nodeexporter:/etc/nodeexporter
    restart: always
#    restart: unless-stopped
    ports:
      - "9100:9100"
#    networks:
#      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
