global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

#  - job_name: 'node'
#    static_configs:
#      - targets: ['localhost:9100']
#      - targets: ['123.45.67.89:9100']

  - job_name: 'Kuber_node_exporter'
    static_configs:
      - targets: ['123.45.67.89:9100']
#      relabel_configs:
#        - source_labels: [--metanode-exporter]
#          regex: 'node-exporter'
#          action: keep
 
#  - job_name: 'node-exporter'
#        kubernetes_sd_configs:
#          - role: endpoints
#        relabel_configs:
#        - source_labels: [__meta_kubernetes_endpoints_name]
#          regex: 'node-exporter'
#          action: keep
#    static_configs:
 #       - targets: ['123.45.67.89:9100']
